name: flow01
on: push

jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: Start Message
        run: echo "Start!"
      - uses: actions/checkout@v2
      - run:
          ls -al
          cd .github/workflows/
          ls -al
      - name: Finish Message
        run: echo "Finish!"