name: flow_1
on: push
env:
  env_1: bb3gen
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Start Message
        run: echo "Start! ${{ env.env_1 }}"
      - uses: actions/checkout@v4
      - run: |
          ls -al
          cd .github/workflows/
          ls -al
      - name: Finish Message
        run: echo "Finish!"